version: '3'

services:
# Define Jenkins Service
  jenkins-master:
    image: 'jenkins/jenkins:lts'
    hostname: 'jenkins.zm-srv-01'
    restart: unless-stopped
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/jenkins-master:/var/jenkins_home

# Define jenkins agent
  jenkins-agent:
    build: .
    image: zm-jenkins-agent-jdk:latest
    restart: unless-stopped
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/jenkins-agent:/home/jenkins

# Define Gitlab Service
  gitlab-ce:
    image: 'gitlab/gitlab-ce:latest'
    hostname: 'gitlab.zm-srv-01'
    restart: unless-stopped
    ports:
      - '8888:80'
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/gitlab-ce:/var/opt/gitlab
