version: '3'

services:
# Define Jenkins Service
  jenkins-master:
    image: 'jenkins/jenkins:lts'
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/jenkins_ci:/var/jenkins_home

# Define jenkins agent
  jenkins-agent:
    build: .
    image: zm-jenkins-agent-jdk:latest
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/jenkins_agent:/home/jenkins

# Define Gitlab Service
  gitlab-ce:
    image: 'gitlab/gitlab-ce:latest'
    ports:
      - '8888:80'
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/gitlab-ce:/var/opt/gitlab
