version: '3'
services:
  jenkins-master:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/jenkins-master:/var/jenkins_home
    #  - jenkins_master:/var/jenkins_home

  jenkins-agent:
    build: .
    image: zm-jenkins-agent-jdk:latest
    volumes:
      - /home/zak/DATA-TO-BACKUP/jenkins-ci/jenkins-agent:/home/jenkins
    #  - jenkins_agent:/home/jenkins

#volumes:
#  jenkins_master:
#  jenkins_agent:
