version: '3'
services:
  jenkins-master:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
      - "22"
    volumes:
      - jenkins_master:/var/jenkins_home

  jenkins-agent:
    build: .
    image: zm-jenkins-agent-jdk:latest
    volumes:
      - jenkins_agent:/home/jenkins

volumes:
  jenkins_master:
  jenkins_agent:
