version: '3'
services:
  jenkins-master:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
      - "22"
    volumes:
      - jenkins_home:/var/jenkins_home

  jenkins-slave:
    build: .
    image: zm-jenkins-slave-jdk:latest
    volumes:
      - jenkins_slave:/home/jenkins

#  jenkins-slave:
#    image: ubuntu:latest
#    command: bash -c "tail -f /dev/null"
#    ports:
#      - "22"

volumes:
  jenkins_home:
  jenkins_slave:
